services:
  mongo:
    image: mongo:7
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - library-network

  backend:
    build:
      context: ./library-backend
      dockerfile: dev.Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./library-backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/library?authSource=admin
      - JWT_SECRET=your-secret-key-here
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - library-network
    container_name: library-backend-dev

  frontend:
    build:
      context: ./library-frontend
      dockerfile: dev.Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./library-frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_GRAPHQL_URI=http://localhost:4000
      - VITE_GRAPHQL_WS_URI=ws://localhost:4000
    depends_on:
      - backend
    networks:
      - library-network
    container_name: library-frontend-dev

  nginx:
    image: nginx:1.25-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - library-network
    container_name: library-nginx-dev

volumes:
  mongo_data:

networks:
  library-network:
    driver: bridge