POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Blog Title 2",
  "author": "Blog Author 2",
  "url": "http://example.com/blog-post",
  "likes": 20,
  "userId": "6840c2eeba01f6b000199205"
}