services:
  mongo:
    image: initialized-mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    
  redis:
    image: redis
    ports:
      - 6378:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data
      
  server:
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./todo-backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    container_name: todo-backend-dev

  frontend:
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    container_name: todo-frontend-dev

  nginx:
    image: nginx:1.25-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - frontend
    container_name: todo-nginx-dev

volumes:
  mongo_data:
  redis_data: