name: Deployment pipeline

on:
  push:
    paths:
      - 'part11/full-stack-open-pokedex/**'
      - '.github/workflows/**' 
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            part11/full-stack-open-pokedex
            .github/workflows
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: ./part11/full-stack-open-pokedex
        run: npm install
      - name: Check style
        working-directory: ./part11/full-stack-open-pokedex
        run: npm run eslint