name: CI/CD Pipeline

on:
  push:
    paths:
      - 'part11/full-stack-open-pokedex/**'
      - '.github/workflows/**' 
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - 'part11/full-stack-open-pokedex/**'
      - '.github/workflows/**'

# env:
#   SKIP_DEPLOYMENT: ${{ github.event_name == 'push' && github.event.commits != null && contains(join(github.event.commits.*.message, ' '), '#skip') }}

jobs:
  # Build, lint, and unit test
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            part11/full-stack-open-pokedex
            .github/workflows
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './part11/full-stack-open-pokedex/package-lock.json'
      - name: Install dependencies
        working-directory: ./part11/full-stack-open-pokedex
        run: npm ci
      - name: Check style
        working-directory: ./part11/full-stack-open-pokedex
        run: npm run eslint
      - name: Build
        working-directory: ./part11/full-stack-open-pokedex
        run: npm run build
      - name: Unit Test
        working-directory: ./part11/full-stack-open-pokedex
        run: npm test

  # E2E tests (runs in parallel with build_and_test)
  e2e_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Skip E2E tests (temporarily disabled)
      run: |
        echo "⚠️ E2E tests are temporarily disabled"
        echo "This job will report as successful to allow dependent jobs to run"
        echo "Re-enable by uncommenting the actual test steps below"
    
    # Temporarily commented out - uncomment to re-enable E2E tests

      # - uses: actions/checkout@v4
      #   with:
      #     sparse-checkout: |
      #       part11/full-stack-open-pokedex
      #       .github/workflows
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      #     cache: 'npm'
      #     cache-dependency-path: './part11/full-stack-open-pokedex/package-lock.json'
      # - name: Install dependencies
      #   working-directory: ./part11/full-stack-open-pokedex
      #   run: npm ci
      # - name: Cache Playwright browsers
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/ms-playwright
      #     key: ${{ runner.os }}-playwright-${{ hashFiles('./part11/full-stack-open-pokedex/package-lock.json') }}
      # - name: Install Playwright Browsers
      #   working-directory: ./part11/full-stack-open-pokedex
      #   run: npx playwright install --with-deps
      # - name: Run Playwright tests
      #   working-directory: ./part11/full-stack-open-pokedex
      #   run: npm run test:e2e
      # - uses: actions/upload-artifact@v4
      #   if: ${{ !cancelled() }}
      #   with:
      #     name: playwright-report
      #     path: ./part11/full-stack-open-pokedex/playwright-report/
      #     retention-days: 30

  # Version tagging (only on push to main, after tests pass, and if not skipped) 
  tag_release:
    needs: [build_and_test, e2e_tests]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c # use the full hash number instead of version number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          DRY_RUN: false

  # Deploy to Render (only on push to main, after tests pass, and if not skipped)
  deploy:
    needs: [build_and_test, e2e_tests]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false

  # Discord notifications
  notify_success:
    needs: [build_and_test, e2e_tests, tag_release, deploy]
    runs-on: ubuntu-latest
    if: ${{ always() && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') && needs.build_and_test.result == 'success' && needs.e2e_tests.result == 'success' && needs.tag_release.result == 'success' && needs.deploy.result == 'success' }}
    steps:
      - name: Success Notification
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: "🚀 Deploy Bot"
          avatarUrl: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          text: "✅ **Deployment Successful!**"
          severity: info
          color: '#00ff00'
          title: "New Version Deployed"
          description: |
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** [`${{ github.sha }}`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            **Author:** ${{ github.actor }}
            **Message:** ${{ github.event.head_commit.message }}
            
            🎉 Application successfully deployed to production!
          footer: "Deployed at ${{ github.run_number }} • ${{ github.workflow }}"

  notify_failure:
    needs: [build_and_test, e2e_tests, tag_release, deploy]
    runs-on: ubuntu-latest
    if: ${{ always() && github.event_name == 'push' && (needs.build_and_test.result == 'failure' || needs.e2e_tests.result == 'failure' || needs.tag_release.result == 'failure' || needs.deploy.result == 'failure') }}
    steps:
      - name: Failure Notification
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: "💥 Build Bot"
          avatarUrl: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          text: "❌ **Build/Deployment Failed!**"
          severity: error
          color: '#ff0000'
          title: "Pipeline Failure"
          description: |
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Failed Commit:** [`${{ github.sha }}`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            **Author:** ${{ github.actor }}
            **Commit Message:** ${{ github.event.head_commit.message }}
            **Workflow:** [${{ github.workflow }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
            **Job Status:**
            🔍 Build & Test: ${{ needs.build_and_test.result }}
            🎭 E2E Tests: ${{ needs.e2e_tests.result }}
            🏷️ Tag Release: ${{ needs.tag_release.result }}
            🚀 Deploy: ${{ needs.deploy.result }}
            
            **Quick Debug Links:**
            • [View Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            • [Compare Changes](${{ github.server_url }}/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.sha }})
          footer: "Failed at run #${{ github.run_number }} • Check logs immediately!"
